style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/quay/quay
options:
  sort: semver
  commits:
    sort_by: Scope
  commit_groups:
    group_by: Scope
  header:
    pattern: '^(.*):\s*(.*)$'
    pattern_maps:
      - Scope
      - Subject
  issues:
    prefix:
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
